import type { Metadata } from "next";
import { LegalHeader, SiteFooter } from "@/components/site-chrome";

export const metadata: Metadata = { title: "Privacy", description: "How Worthlane handles account, financial, and device data." };
const CONTACT_EMAIL = "support@worthlane.app";

export default function PrivacyPage() {
  return <><LegalHeader /><main className="legal-page"><article className="site-container legal-copy"><p className="eyebrow">Worthlane policies</p><h1>Privacy, plainly put.</h1><p>Effective July 10, 2026. This page explains how Worthlane handles the information used to provide the mobile app.</p><section><h2>Information we use</h2><p>When you create an account, Worthlane stores your email address and a securely hashed password. The app also stores the accounts, transactions, categories, budgets, goals, streaks, and preferences you add so it can show your financial picture.</p><p>If you enable push notifications, Worthlane stores a device push token so it can send budget alerts, streak reminders, and other app notifications you have chosen to receive.</p></section><section><h2>How it is used</h2><ul><li>To authenticate you and operate the app.</li><li>To calculate budgets, goals, net worth, and financial insights.</li><li>To provide the in-app financial assistant with the context needed to answer your questions.</li><li>To send opted-in notifications and respond to support requests.</li></ul></section><section><h2>Bank linking</h2><p>Automatic bank linking is not enabled in version 1. When it is introduced, Worthlane plans to use Plaid for the bank connection flow. Plaid handles bank credentials; Worthlane does not receive or store those credentials. Bank access tokens, if used in a future version, are encrypted before they are stored.</p></section><section><h2>Keeping control</h2><p>You can remove linked account data from your profile and delete your Worthlane account inside the app. Account deletion permanently removes your account and associated financial data from our systems, subject to any retention required by law.</p></section><section><h2>Contact</h2><p>For privacy questions or requests, contact <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p></section><aside className="legal-callout"><strong>Legal review required.</strong> This launch policy is a product-facing summary and should be reviewed by qualified counsel before the public release, particularly before bank linking or analytics settings change.</aside></article></main><SiteFooter /></>;
}
